### ISSUE TITLE
Investor update

### ISSUE THREAD

**Issue by pakaplace** [DemocracyEarth/ubi#26]
Hi Santi, first off, I apologize for using a github issue as a medium for communication. I had no luck trying the @democracy.earth emails or twitter account, which I emailed several times in 2020.

I was wondering if you could give an investor update. You can reach out to me directly and for reference, my address is `0x365...065`. 

The last update (in 2019) detailed plans for a $VOTE token architecture, which seemed to have been abandoned. I understand, but as a backer, I'm wondering at this point what I've funded. I'd prefer to have my funds returned or at the very least, a plan, a reply, really anything.

**Comment by santisiri** [comment]
hi @pakaplace, I haven't seen your email but you should've gotten our investor update from last year. We have credited all our investors with the $hour token in 2019 which was a rebranding we explored for the $vote token. That said: we have been developing the dapp during this period (https://democracy.earth) and the token being developed on this repo —$ubi— will be launched in Q1 of 2021 and all investors that took place of the $hour token will get their equivalent share. 

I can't disclose in public details of the launch yet, but you can expect liquidity farming pools and a new product we are building alongside Kleros. Ping me in private for more details.

**Comment by pakaplace** [comment]
Thank you, and btw I had emailed @herb and @hello. What is the best way to get in touch?
