### ISSUE TITLE
UBI Token Review

### ISSUE THREAD

**Issue by fnanni-0** [DemocracyEarth/ubi#36]
https://docs.google.com/document/d/1FHmn5Xwk8ECfjV76YiqCNj39uLGNyBLd3qt-OWHdOs4/edit?usp=sharing

**Comment by santisiri** [comment]
Thanks @fnanni-0, looking into the review right now.

**Comment by santisiri** [comment]
#39 https://github.com/DemocracyEarth/ubi/pull/39

Kept the simplistic approach yet I think in the future we could improve accrual mechanism with something analogue to how rebasing works in [Ampleforth](https://github.com/ampleforth/uFragments/blob/master/contracts/UFragments.sol)

**Comment by fnanni-0** [comment]
Beware that the current snapshot id is not visible to external contracts directly. You can only access it by querying the Snapshot event. I'm not sure if this could become an issue in the future. You might want to make the [snapshot()](https://github.com/DemocracyEarth/ubi/blob/d931ae896c6d9c91acafbccecb7153f42bf5f387/contracts/UBI.sol#L187-L189) function return the current id, and maybe even store it.

**Comment by santisiri** [comment]
Hi @fnanni-0 , took your advice and implemented here.. looks like after all is probably better to bring upfront the functionality of `snapshot` itself to the main contract. check the changes here: https://github.com/DemocracyEarth/ubi/compare/issuance

**Comment by fnanni-0** [comment]
@santisiri that won't work because you can't override the private variable `_currentSnapShortId`.

I think it would be enough to just return the new id:
```solidity
  function snapshot() external onlyByGovernor returns(uint256) {
    return _snapshot();
  }
```

**Comment by santisiri** [comment]
Ah.. I see.. now that makes sense. Thanks @fnanni-0, will fix and merge now.
