### ISSUE TITLE
What are the addresses on Mainnet and testnet?

### ISSUE THREAD

**Issue by developerfred** [DemocracyEarth/ubi#40]
I'm going to build a subgraph for the project, so more Dapps can be integrated.

**Comment by santisiri** [comment]
Oh wow this is fantastic news! Actually.. we should talk also about https://github.com/DemocracyEarth/dapp regarding subgraphs.

The token and Proof of Humanity haven't been deployed to the Mainnet yet. We expect the launch to happen soon, definitely Q1 of 2021.

**Comment by santisiri** [comment]
In `kovan` the token can be found at `0xDdAdE19B13833d1bF52c1fe1352d41A8DD9fE8C9`

**Comment by developerfred** [comment]
> Oh wow this is fantastic news! Actually.. we should talk also about https://github.com/DemocracyEarth/dapp regarding subgraphs.
> 
> The token and Proof of Humanity haven't been deployed to the Mainnet yet. We expect the launch to happen soon, definitely Q1 of 2021.

Perfect, I will create the subgraph after I integrate the project App
