### ISSUE TITLE
Stream tokens directly to humans

### ISSUE THREAD

**Issue by auryn-macmillan** [DemocracyEarth/ubi#51]
The current token design requires humans to call `mintAccrued(address human)` any time they want to claim their outstanding UBI balance. With the current gas price swings, that transaction is likely to cost tens to hundreds of dollars.

An alternate option is to have the ERC20 `balanceOf()` be a computed variable, based on incoming and outgoing streams to the address. [Superfluid](https://www.superfluid.finance/) has built out this functionality already, so implementing this would be really simple.

**Comment by santisiri** [comment]
Will definitely explore this possibility. This is a great idea @auryn-macmillan !

**Comment by mdalie** [comment]
That sounds pretty awesome @auryn-macmillan, we would be glad to help you integrate [Superfluid](https://docs.superfluid.finance/superfluid/). @santisiri join our [Discord](https://discord.gg/qKgxvzr) so we can talk about it.

**Comment by santisiri** [comment]
Working my way through the documentation to test `superTokens`.. stuck here for time being: https://github.com/superfluid-finance/protocol-monorepo/issues/230

**Comment by mdalie** [comment]
I see on [Discord](https://discord.gg/qKgxvzr) that you and our champion @pi0neerpat are on it, shout if you have any issues.

**Comment by santisiri** [comment]
Been testing this out and looking at the contracts. Since we know that our `ubi` contract can mint tokens throughout time to valid identities, been thinking we could simply implement the functionality related to `realtimeBalanceOf`:

```Solidity
function balanceOf(
        address account
    )
        public
        view
        override
        returns(uint256 balance)
    {
        // solhint-disable-next-line not-rely-on-time
        (int256 availableBalance, , ) = super.realtimeBalanceOf(account, block.timestamp);
        return availableBalance < 0 ? 0 : uint256(availableBalance);
    }
```

Though for this I'd like to have a clearer picture for security precautions we need to consider. Probably making this optional on a first version makes sense cc @epiqueras.

**Comment by santisiri** [comment]
Implemented a very simple version that directly displays accrued value on `balanceOf` — pull available here: https://github.com/DemocracyEarth/ubi/pull/73

**Comment by santisiri** [comment]
eppur si muove: https://twitter.com/santisiri/status/1363503509145079811

thanks for pushing me in this direction @auryn-macmillan !

**Comment by auryn-macmillan** [comment]
This is awesome!

**Comment by santisiri** [comment]
Feature implemented, audited and tested. Closing.
