### ISSUE TITLE
Implement `_msg.sender()` for meta-transaction for the UBI token

### ISSUE THREAD

**Issue by n1c01a5** [DemocracyEarth/ubi#76]
Maybe it can be useful to inherit the UBI smart contract from `BaseRelayRecipient.sol` https://github.com/opengsn/gsn/blob/master/packages/contracts/src/BaseRelayRecipient.sol to allow metaTx.

Cons: more gas / more complexity

**Comment by santisiri** [comment]
This is definitely an interesting feature, but right now we are currently aggressively optimizing gas consumption of the contract as we are ready to deploy on mainnet.
