### ISSUE TITLE
Add permit feature to UBI

### ISSUE THREAD

**Issue by fnanni-0** [DemocracyEarth/ubi#92]
This is an idea for a new feature.

UBI holders won't necessarily have ETH to pay for the gas used in transactions nor the money to buy ETH. Implementing something like https://eips.ethereum.org/EIPS/eip-2612 into UBI token would allow low income users to transact UBIs in a gasless way by using signatures and letting the recipient of the transaction pay for the gas.

This one might be useful as well: https://eips.ethereum.org/EIPS/eip-3009.

**Comment by EngineerWasat** [comment]
mistx.io?

**Comment by donosonaumczuk** [comment]
I recommend using OpenZeppelin [ERC20 extension with permit function](https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/extensions/draft-ERC20Permit.sol).

**Comment by santisiri** [comment]
I will explore this once we finish the work adapting EIP 1620 to make the token streamable. @donosonaumczuk if you'd like to explore on a specific branch for this, let me know.

**Comment by donosonaumczuk** [comment]
I will be implementing [EIP-2612: permit](https://eips.ethereum.org/EIPS/eip-2612) for UBI. Once become ready I will reference a pull request here.

**Comment by donosonaumczuk** [comment]
[UIP-2: Adding EIP-2612 permit function to UBI](https://gov.proofofhumanity.id/t/phase-1-uip-2-adding-eip-2612-permit-function-to-ubi/1030) created!

**Comment by santisiri** [comment]
Merged on master.
